defaults:
- common

spk_encoder_ckpt: models/speaker_encoder/ckpt/pretrained_bak_5805000.pt
ssl_encoder_type: wavlm
ssl_encoder_ckpt: models/wavlm/WavLM-Large.pt
post_ssl_encoder_type: freevc-bottleneck
cond_lang: true
coarse_f0: true
# lang_dim: 4
lang_dim: 192
num_langs: 3
lang_dict:
  en: 0
  jp: 1
  zh: 2


data:
  dataset_dir: metadata
  filter_length: 1280
  hop_length: 320
  max_wav_value: 32768.0
  mel_fmax: null
  mel_fmin: 0.0
  n_mel_channels: 80
  num_workers: 16
  pitch_features_dir: null
  sampling_rate: 16000
  spectrogram_dir: null
  spk_embeddings_dir: null
  sr_min_max: [68, 92]
  ssl_feature_dir: null
  training_files: ${data.dataset_dir}/train.csv
  validation_files: ${data.dataset_dir}/val.csv
  win_length: 1280

train:
  batch_size: 32
  betas: [0.8, 0.99]
  c_kl: 1.0
  c_mel: 45
  distributed: true
  epochs: 10000
  eps: 1e-9
  fp16_run: false
  init_lr_ratio: 1
  raise_error: true
  learning_rate: 2e-4
  log_interval: 200
  log_level: INFO
  lr_decay: 0.999875
  max_speclen: 128
  port: 8001
  resume_training: true
  seed: 1234
  segment_size: 8960
  use_multiprocessing: false
  use_sr: false
  valid_epoch_interval: 1
  valid_steps_interval: 1000
  save_epoch_interval: 10
  save_steps_interval: 1000
  warmup_epochs: 0
  weighted_batch_speaker_sampling : true

model:
  save_dir: null
  filter_channels: 768
  finetune_from_model:
    discriminator: null
    generator: null
  gin_channels: 256
  hidden_channels: 192
  inter_channels: 192
  kernel_size: 3
  n_heads: 2
  n_layers_q: 3
  n_layers: 6
  p_dropout: 0.1
  resblock_dilation_sizes: [[1,3,5], [1,3,5], [1,3,5]]
  resblock_kernel_sizes: [3,7,11]
  resblock: 1
  ssl_dim: 1024
  upsample_initial_channel: 512
  upsample_kernel_sizes: [16,16,4,4]
  upsample_rates: [10,8,2,2]
  use_spectral_norm: false
  use_spk: false